## 内積とか行列の積とか

In [11]:
import numpy as np

In [19]:
a = np.arange(1, 5)
print(a)

[1 2 3 4]


要素が4つの行列を生成

In [20]:
a = a.reshape(2,2)
print(a)

[[1 2]
 [3 4]]


2 * 2の行列を生成

In [21]:
print(a.T)

[[1 3]
 [2 4]]


転置

In [41]:
a = ([1, 2])
b = ([2, 3])

print(np.dot(a, b))

8


np.dotでベクトルの内積(a・b)

In [42]:
print(np.dot(a, a))

5


aのノルムの2乗

In [39]:
a = np.arange(1, 5).reshape(2, 2)
b = np.arange(5, 9).reshape(2, 2)

print(a)
print()
print(b)
print()
print(np.dot(a, b))

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[19 22]
 [43 50]]


np.dotで行列の積も