## 階数(ランク)

In [3]:
import numpy as np
import numpy.linalg as LA

In [4]:
A = np.array([[1, 1, 4, 0, 1], 
                      [0, 3, 1, 3, 2],
                      [1, 3, 0, 0, 1],
                      [2, 4, 3, 1, 1]])

print(LA.matrix_rank(A))

4


## 逆行列

### 概要
- *A A^*-1 = *I* となる*A^*-1 がAの逆行列


### 求め方
1. Ainv = (余因子行列) / detA
1. Aに単位行列 I を併設し、Aが単位行列になるまで行基本変形をしたら、I の部分がAinvになっている。

In [11]:
A = np.array([[-1, 4], [0, -2]])
print("A = ")
print(A)
print()

Ainv = LA.inv(A)
print("A^-1 = ")
print(Ainv)
print()

print("AA^-1 = I")
print(np.dot(A, Ainv))

A = 
[[-1  4]
 [ 0 -2]]

A^-1 = 
[[-1.  -2. ]
 [-0.  -0.5]]

AA^-1 = I
[[1. 0.]
 [0. 1.]]


### 正則行列

- 以下のどれかを満たすと、n×nの正方行列は正則行列と言える。
    1. 逆行列が存在する
    1. 行列式が0でない
    1. ランクがn
    1. カーネルは**0**のみ
        - 参考…次元定理 : rankA + rank(KerA) = n
    1. 固有値が全て0でない

## 直積

In [14]:
a = np.array([1, 2, 3, 2, 1])
b = np.array([0, 2, 4, 6, 8, 1])

AB = np.outer(a, b)
print(AB)
print()

# 直積のi j 成分 = a[i] * b[j]
print(AB[2][4] == a[2] * b[4])

[[ 0  2  4  6  8  1]
 [ 0  4  8 12 16  2]
 [ 0  6 12 18 24  3]
 [ 0  4  8 12 16  2]
 [ 0  2  4  6  8  1]]

True
